// Generated by CoffeeScript 1.7.1
(function() {
  describe('Lisp', function() {
    return describe('parser', function() {
      it('should not thrown', function() {
        expect(function() {
          return (new Parser).parse('(1 "hoge" nil t \'(1 2 3))');
        }).not.to["throw"]();
        expect(function() {
          return (new Parser).parse('(cons 0 \'(1 2 3))');
        }).not.to["throw"]();
        expect(function() {
          return (new Parser).parse('(cond ((eq 1 1) "hoge") ((eq 2 2) "piyo"))');
        }).not.to["throw"]();
        return expect(function() {
          return (new Parser).parse('(quote (1 2 3))');
        }).not.to["throw"]();
      });
      return it('should thrown', function() {
        return expect(function() {
          return (new Parser).parse('(');
        }).to["throw"]();
      });
    });
  });

}).call(this);
